- id: supyrliminal
  name: Supyrliminal
  description: "Run flake8 with SL (Supyrliminal) and PYD checks"
  entry: flake8 --select=SL,PYD
  language: python
  types_or: [python, pyi]
  args: []
  require_serial: true
  additional_dependencies:
    - flake8>=5.0
    - flake8-pydantic>=0.4
  minimum_pre_commit_version: "3.0.0"
